name: "Go: Run Tests"
on:
  push:
    paths:
      - "go/**"
      - "shared/**"
      - .github/workflows/go-tests.yml
      - .github/actions/**
      - codeql-workspace.yml
    branches:
      - main
      - "rc/*"
  pull_request:
    paths:
      - "go/**"
      - "shared/**"
      - .github/workflows/go-tests.yml
      - .github/actions/**
      - codeql-workspace.yml
      - MODULE.bazel
      - .bazelrc
      - misc/bazel/**

permissions:
  contents: read

jobs:
  test-linux:
    if: github.repository_owner == 'FreeMason9224'
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15, 1.16, 1.17]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./...
      - name: Run code checks
        run: |
          if [ "${{ matrix.go-version }}" == "1.17" ]; then
            go vet ./...
          fi
